/* DragonMax device runtime - a MAX-compatible device ABI over OpenCL.
 *
 * This implements the `AsyncRT_*` C symbols that Mojo's
 * `max/mojo/max/gpu/host/device_context.mojo` calls into. Modular does not
 * publish an implementation, but the bindings declare every symbol, so the
 * interface is fully specified - see `ABI.md`, generated by extract_abi.py.
 *
 * Implement these and Mojo's `DeviceContext`, `DeviceBuffer` and
 * `enqueue_function` work unchanged on the Adreno. Mojo code stays standard
 * Mojo; nothing about the language or the kernel library is reinvented.
 *
 * Scope here is the 33-symbol bring-up subset: enough to create a context,
 * allocate, copy both ways, load a kernel, launch it, and synchronise.
 *
 * Conventions taken from the bindings and matched exactly:
 *   - Most calls return `const char *`: NULL is success, non-NULL is an error
 *     message the CALLER owns and must release via
 *     `AsyncRT_DeviceContext_strfree`. Get this wrong and every error path
 *     leaks.
 *   - Handles are opaque, reference counted, with explicit retain/release.
 *   - Launch dimensions are `uint32_t`, not `int64_t`. The bindings warn that
 *     Mojo has two launch paths and they must agree, or a module composing
 *     both fails to legalize.
 */

#include <algorithm>
#include <atomic>
#include <cstdarg>
#include <cstdlib>
#include <cstdint>
#include <cstdio>
#include <cctype>
#include <cstring>
#include <mutex>
#include <string>
#include <vector>

#include <windows.h>

/* ---- OpenCL, declared not included (no SDK on this machine) ------------- */

typedef void *cl_platform_id, *cl_device_id, *cl_context, *cl_command_queue;
typedef void *cl_mem, *cl_program, *cl_kernel, *cl_event;
typedef int cl_int;
typedef unsigned int cl_uint;
typedef unsigned long long cl_ulong, cl_bitfield;

#define CL_SUCCESS 0
#define CL_PLATFORM_NAME 0x0902
#define CL_DEVICE_NAME 0x102B
#define CL_DEVICE_TYPE_ALL 0xFFFFFFFF
#define CL_DEVICE_GLOBAL_MEM_SIZE 0x101F
#define CL_DEVICE_MAX_MEM_ALLOC_SIZE 0x1010
#define CL_DEVICE_VERSION 0x102C
#define CL_MEM_READ_WRITE (1 << 0)
#define CL_MEM_ALLOC_HOST_PTR (1 << 4)
#define CL_TRUE 1
#define CL_FALSE 0
#define CL_PROGRAM_BUILD_LOG 0x1183
#define CL_QUEUE_PROFILING_ENABLE (1 << 1)

#define CLFN(ret, name, ...)                                                   \
    typedef ret(__stdcall *pfn_##name)(__VA_ARGS__);                           \
    static pfn_##name name;

CLFN(cl_int, clGetPlatformIDs, cl_uint, cl_platform_id *, cl_uint *)
CLFN(cl_int, clGetPlatformInfo, cl_platform_id, cl_uint, size_t, void *, size_t *)
CLFN(cl_int, clGetDeviceIDs, cl_platform_id, cl_bitfield, cl_uint, cl_device_id *,
     cl_uint *)
CLFN(cl_int, clGetDeviceInfo, cl_device_id, cl_uint, size_t, void *, size_t *)
CLFN(cl_context, clCreateContext, void *, cl_uint, const cl_device_id *, void *,
     void *, cl_int *)
CLFN(cl_int, clReleaseContext, cl_context)
CLFN(cl_command_queue, clCreateCommandQueue, cl_context, cl_device_id, cl_bitfield,
     cl_int *)
CLFN(cl_int, clReleaseCommandQueue, cl_command_queue)
CLFN(cl_mem, clCreateBuffer, cl_context, cl_bitfield, size_t, void *, cl_int *)
CLFN(cl_int, clReleaseMemObject, cl_mem)
CLFN(cl_program, clCreateProgramWithSource, cl_context, cl_uint, const char **,
     const size_t *, cl_int *)
CLFN(cl_program, clCreateProgramWithIL, cl_context, const void *, size_t, cl_int *)
CLFN(cl_int, clBuildProgram, cl_program, cl_uint, const cl_device_id *, const char *,
     void *, void *)
CLFN(cl_int, clGetProgramInfo, cl_program, cl_uint, size_t, void *, size_t *)
CLFN(cl_int, clGetProgramBuildInfo, cl_program, cl_device_id, cl_uint, size_t, void *,
     size_t *)
CLFN(cl_int, clReleaseProgram, cl_program)
CLFN(cl_kernel, clCreateKernel, cl_program, const char *, cl_int *)
CLFN(cl_int, clReleaseKernel, cl_kernel)
CLFN(cl_int, clSetKernelArg, cl_kernel, cl_uint, size_t, const void *)
CLFN(cl_int, clEnqueueWriteBuffer, cl_command_queue, cl_mem, cl_uint, size_t, size_t,
     const void *, cl_uint, const cl_event *, cl_event *)
CLFN(cl_int, clEnqueueReadBuffer, cl_command_queue, cl_mem, cl_uint, size_t, size_t,
     void *, cl_uint, const cl_event *, cl_event *)
CLFN(cl_int, clEnqueueCopyBuffer, cl_command_queue, cl_mem, cl_mem, size_t, size_t,
     size_t, cl_uint, const cl_event *, cl_event *)
CLFN(cl_int, clEnqueueFillBuffer, cl_command_queue, cl_mem, const void *, size_t,
     size_t, size_t, cl_uint, const cl_event *, cl_event *)
CLFN(cl_int, clEnqueueNDRangeKernel, cl_command_queue, cl_kernel, cl_uint,
     const size_t *, const size_t *, const size_t *, cl_uint, const cl_event *,
     cl_event *)
CLFN(cl_int, clFinish, cl_command_queue)
CLFN(void *, clGetExtensionFunctionAddressForPlatform, cl_platform_id, const char *)

static bool g_clLoaded = false;

static bool loadCL() {
    if (g_clLoaded) return true;
    HMODULE h = LoadLibraryA("OpenCL.dll");
    if (!h) return false;
#define GET(name)                                                              \
    name = (pfn_##name)GetProcAddress(h, #name);                               \
    if (!name && strcmp(#name, "clCreateProgramWithIL") != 0) return false;
    GET(clGetPlatformIDs) GET(clGetPlatformInfo) GET(clGetDeviceIDs)
    GET(clGetDeviceInfo) GET(clCreateContext) GET(clReleaseContext)
    GET(clCreateCommandQueue) GET(clReleaseCommandQueue) GET(clCreateBuffer)
    GET(clReleaseMemObject) GET(clCreateProgramWithSource)
    GET(clCreateProgramWithIL) GET(clBuildProgram) GET(clGetProgramBuildInfo)
    GET(clGetProgramInfo)
    GET(clReleaseProgram) GET(clCreateKernel) GET(clReleaseKernel)
    GET(clSetKernelArg) GET(clEnqueueWriteBuffer) GET(clEnqueueReadBuffer)
    GET(clEnqueueCopyBuffer) GET(clEnqueueFillBuffer)
    GET(clEnqueueNDRangeKernel) GET(clFinish)
    GET(clGetExtensionFunctionAddressForPlatform)
#undef GET
    g_clLoaded = true;
    return true;
}

/* ---- error strings ------------------------------------------------------
 * NULL means success. Anything else is owned by the caller and released with
 * AsyncRT_DeviceContext_strfree.
 */

static const char *errf(const char *fmt, ...) {
    char buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    size_t n = strlen(buf) + 1;
    char *out = (char *)malloc(n);
    if (out) memcpy(out, buf, n);
    return out;
}

/* ---- handles ------------------------------------------------------------ */

struct DragonContext;

struct DragonStream {
    std::atomic<int> rc{1};
    cl_command_queue q = nullptr;
    DragonContext *ctx = nullptr;
};

struct DragonBuffer {
    std::atomic<int> rc{1};
    cl_mem mem = nullptr;
    size_t bytes = 0;
    DragonContext *ctx = nullptr;
    void *hostPtr = nullptr;  /* set for host buffers */
    bool owning = true;
};

struct DragonFunction {
    std::atomic<int> rc{1};
    cl_program prog = nullptr;
    cl_kernel kern = nullptr;
    DragonContext *ctx = nullptr;
};

/* Resolved per PLATFORM via clGetExtensionFunctionAddressForPlatform. The
 * loader's core clCreateProgramWithIL slot ACCESS-VIOLATES on an OpenCLOn12
 * context (measured 2026-08-19, read at offset 0x38 inside the dispatch);
 * only the KHR extension pointer is safe. Never call the core symbol. */
typedef cl_program(__stdcall *pfn_createProgramWithILKHR)(cl_context, const void *,
                                                          size_t, cl_int *);

struct DragonContext {
    std::atomic<int> rc{1};
    cl_context cl = nullptr;
    cl_device_id dev = nullptr;
    cl_platform_id plat = nullptr;
    std::string platName;
    pfn_createProgramWithILKHR ilCreate = nullptr;
    DragonStream *defaultStream = nullptr;
    std::vector<DragonStream *> streams;
    std::mutex lock;
    int id = 0;
    std::string name, arch, api;
};

/* The ABI hands `deviceApi` back as an llvm::StringRef. That is just a pointer
 * and a length, so it is reproduced here rather than dragging in LLVM - but it
 * is worth flagging that this ABI is not pure C. */
struct StringRefABI {
    const char *data;
    size_t length;
};

/* ---- device selection ---------------------------------------------------
 * By PLATFORM, never by device name: OpenCLOn12 reports the same device string
 * as the native Qualcomm driver, so name matching alone can land anywhere.
 *
 * Measured 2026-08-19 (probe_adreno_spirv.py): the native QUALCOMM platform
 * has NO SPIR-V ingestion at all (empty CL_DEVICE_IL_VERSION, no
 * cl_khr_il_program), while OpenCLOn12 ingests AND executes kernel-flavor
 * SPIR-V on the same Adreno, via D3D12. So the two platforms split the
 * capabilities: native = fastest for SOURCE, On12 = the only IL path today.
 *
 * Selection policy: prefer an IL-capable Adreno platform (the Mojo pipeline
 * ships SPIR-V, which is this runtime's whole purpose), unless
 * DRAGONRT_PREFER=native asks for the source-only native driver (useful for
 * benchmarking the D3D12 tax). A native driver that gains IL in a future
 * update wins automatically, because native platforms are scanned first.
 */

#define CL_DEVICE_IL_VERSION_QUERY 0x105B
#define CL_DEVICE_EXTENSIONS_QUERY 0x1030

static bool deviceHasIL(cl_device_id d) {
    char il[128] = {0};
    if (clGetDeviceInfo(d, CL_DEVICE_IL_VERSION_QUERY, sizeof(il), il, nullptr) ==
            CL_SUCCESS &&
        il[0])
        return true;
    size_t n = 0;
    clGetDeviceInfo(d, CL_DEVICE_EXTENSIONS_QUERY, 0, nullptr, &n);
    if (!n) return false;
    std::string exts(n, '\0');
    clGetDeviceInfo(d, CL_DEVICE_EXTENSIONS_QUERY, n, exts.data(), nullptr);
    return exts.find("cl_khr_il_program") != std::string::npos;
}

static bool pickAdreno(cl_platform_id *outP, cl_device_id *outD, bool *outIL,
                       std::string *outPlatName) {
    cl_uint np = 0;
    if (clGetPlatformIDs(0, nullptr, &np) != CL_SUCCESS || np == 0) return false;
    std::vector<cl_platform_id> ps(np);
    clGetPlatformIDs(np, ps.data(), nullptr);

    struct Cand {
        cl_platform_id p;
        cl_device_id d;
        bool il;
        bool native;
        std::string name;
    };
    std::vector<Cand> cands;
    for (cl_uint i = 0; i < np; ++i) {
        char nm[256] = {0};
        clGetPlatformInfo(ps[i], CL_PLATFORM_NAME, sizeof(nm), nm, nullptr);
        cl_uint nd = 0;
        if (clGetDeviceIDs(ps[i], CL_DEVICE_TYPE_ALL, 0, nullptr, &nd) != CL_SUCCESS ||
            nd == 0)
            continue;
        std::vector<cl_device_id> ds(nd);
        clGetDeviceIDs(ps[i], CL_DEVICE_TYPE_ALL, nd, ds.data(), nullptr);
        for (cl_device_id d : ds) {
            char dn[256] = {0};
            clGetDeviceInfo(d, CL_DEVICE_NAME, sizeof(dn), dn, nullptr);
            if (!strstr(dn, "Adreno")) continue;  /* never the Basic Render Driver */
            cands.push_back({ps[i], d, deviceHasIL(d),
                             strstr(nm, "QUALCOMM") != nullptr, nm});
            break;
        }
    }
    if (cands.empty()) return false;

    /* Native platforms first within each capability class. */
    std::stable_sort(cands.begin(), cands.end(),
                     [](const Cand &a, const Cand &b) { return a.native > b.native; });

    const char *pref = getenv("DRAGONRT_PREFER");
    bool wantNative = pref && strcmp(pref, "native") == 0;
    const Cand *chosen = nullptr;
    if (!wantNative) {
        for (const Cand &c : cands)
            if (c.il) { chosen = &c; break; }
    }
    if (!chosen) chosen = &cands.front();

    *outP = chosen->p;
    *outD = chosen->d;
    *outIL = chosen->il;
    if (outPlatName) *outPlatName = chosen->name;
    return true;
}

extern "C" {

/* ---- context lifecycle -------------------------------------------------- */

__declspec(dllexport) const char *AsyncRT_DeviceContext_create(
    const DragonContext **result, const char *api, int id) {
    if (!result) return errf("AsyncRT_DeviceContext_create: result is null");
    if (!loadCL()) return errf("cannot load OpenCL.dll");

    std::string want = api ? api : "";
    if (want != "adreno" && want != "opencl" && want != "gpu" && !want.empty())
        return errf("DragonMax runtime does not implement api '%s' "
                    "(supported: adreno, opencl, gpu)",
                    want.c_str());

    cl_platform_id p = nullptr;
    cl_device_id d = nullptr;
    bool hasIL = false;
    std::string platName;
    if (!pickAdreno(&p, &d, &hasIL, &platName))
        return errf("no Adreno OpenCL platform found");

    cl_int err = CL_SUCCESS;
    /* With two platforms installed, clCreateContext(NULL props) is ambiguous
     * (OpenCLOn12 returns null). Always name the platform. */
    const intptr_t kClContextPlatform = 0x1084;
    intptr_t props[3] = {kClContextPlatform, (intptr_t)p, 0};
    cl_context cl =
        clCreateContext((void *)props, 1, &d, nullptr, nullptr, &err);
    if (err != CL_SUCCESS) return errf("clCreateContext failed: %d", err);

    auto *c = new DragonContext();
    c->cl = cl;
    c->dev = d;
    c->plat = p;
    c->platName = platName;
    c->id = id;
    c->api = "adreno";
    if (hasIL)
        c->ilCreate = (pfn_createProgramWithILKHR)
            clGetExtensionFunctionAddressForPlatform(p, "clCreateProgramWithILKHR");

    char nm[256] = {0};
    clGetDeviceInfo(d, CL_DEVICE_NAME, sizeof(nm), nm, nullptr);
    c->name = nm;
    char ver[256] = {0};
    clGetDeviceInfo(d, CL_DEVICE_VERSION, sizeof(ver), ver, nullptr);
    c->arch = ver;

    auto *s = new DragonStream();
    s->q = clCreateCommandQueue(cl, d, 0, &err);
    if (err != CL_SUCCESS) {
        delete s;
        clReleaseContext(cl);
        delete c;
        return errf("clCreateCommandQueue failed: %d", err);
    }
    s->ctx = c;
    c->defaultStream = s;
    c->streams.push_back(s);

    *result = c;
    return nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceContext_retain(const DragonContext *ctx) {
    if (ctx) const_cast<DragonContext *>(ctx)->rc.fetch_add(1);
}

__declspec(dllexport) void AsyncRT_DeviceContext_release(const DragonContext *ctx) {
    if (!ctx) return;
    auto *c = const_cast<DragonContext *>(ctx);
    if (c->rc.fetch_sub(1) != 1) return;
    for (auto *s : c->streams) {
        if (s->q) clReleaseCommandQueue(s->q);
        delete s;
    }
    if (c->cl) clReleaseContext(c->cl);
    delete c;
}

__declspec(dllexport) int64_t AsyncRT_DeviceContext_id(const DragonContext *ctx) {
    return ctx ? ctx->id : -1;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_deviceName(
    const DragonContext *ctx) {
    return ctx ? errf("%s", ctx->name.c_str()) : errf("<null>");
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_archName(
    const DragonContext *ctx) {
    return ctx ? errf("%s", ctx->arch.c_str()) : errf("<null>");
}

__declspec(dllexport) void AsyncRT_DeviceContext_deviceApi(StringRefABI *result,
                                                           const DragonContext *ctx) {
    static const char kApi[] = "adreno";
    if (!result) return;
    result->data = kApi;
    result->length = sizeof(kApi) - 1;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_getApiVersion(
    int *result, const DragonContext *ctx) {
    if (result) *result = 300; /* OpenCL 3.0 */
    return nullptr;
}

__declspec(dllexport) int32_t *AsyncRT_DeviceContext_numberOfDevices(const char *kind) {
    static int32_t n = 0;
    n = 0;
    if (loadCL()) {
        cl_platform_id p;
        cl_device_id d;
        bool il;
        if (pickAdreno(&p, &d, &il, nullptr)) n = 1;
    }
    return &n;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_synchronize(
    const DragonContext *ctx) {
    if (!ctx) return errf("synchronize: null context");
    auto *c = const_cast<DragonContext *>(ctx);
    std::lock_guard<std::mutex> g(c->lock);
    for (auto *s : c->streams) {
        cl_int e = clFinish(s->q);
        if (e != CL_SUCCESS) return errf("clFinish failed: %d", e);
    }
    return nullptr;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_setAsCurrent(
    const DragonContext *ctx) {
    /* OpenCL has no current-context concept; contexts are explicit. */
    return nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceContext_strfree(const char *ptr) {
    free((void *)ptr);
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_getMemoryInfo(
    const DragonContext *ctx, size_t *freeMem, size_t *totalMem) {
    if (!ctx) return errf("getMemoryInfo: null context");
    cl_ulong total = 0;
    clGetDeviceInfo(ctx->dev, CL_DEVICE_GLOBAL_MEM_SIZE, sizeof(total), &total,
                    nullptr);
    if (totalMem) *totalMem = (size_t)total;
    /* OpenCL exposes no free-memory query; report total. Better an honest
     * over-estimate than a fabricated number. */
    if (freeMem) *freeMem = (size_t)total;
    return nullptr;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_maxSingleAllocationSize(
    size_t *result, const DragonContext *ctx) {
    if (!ctx) return errf("maxSingleAllocationSize: null context");
    cl_ulong mx = 0;
    clGetDeviceInfo(ctx->dev, CL_DEVICE_MAX_MEM_ALLOC_SIZE, sizeof(mx), &mx, nullptr);
    if (result) *result = (size_t)mx;
    return nullptr;
}

/* ---- buffers ------------------------------------------------------------ */

__declspec(dllexport) const char *AsyncRT_DeviceContext_createBuffer_async(
    const DragonBuffer **result, void **device_ptr, const DragonContext *ctx,
    size_t len, size_t elem_size) {
    if (!ctx) return errf("createBuffer_async: null context");
    size_t bytes = len * elem_size;
    cl_int err = CL_SUCCESS;
    cl_mem m = clCreateBuffer(ctx->cl, CL_MEM_READ_WRITE, bytes, nullptr, &err);
    if (err != CL_SUCCESS) return errf("clCreateBuffer(%zu) failed: %d", bytes, err);
    auto *b = new DragonBuffer();
    b->mem = m;
    b->bytes = bytes;
    b->ctx = const_cast<DragonContext *>(ctx);
    if (result) *result = b;
    /* Mojo treats this as an opaque device address; the cl_mem handle is it. */
    if (device_ptr) *device_ptr = (void *)m;
    return nullptr;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_createHostBuffer(
    const DragonBuffer **result, void **device_ptr, const DragonContext *ctx,
    size_t len, size_t elem_size) {
    if (!ctx) return errf("createHostBuffer: null context");
    size_t bytes = len * elem_size;
    void *host = malloc(bytes);
    if (!host) return errf("createHostBuffer: out of memory (%zu)", bytes);
    auto *b = new DragonBuffer();
    b->hostPtr = host;
    b->bytes = bytes;
    b->ctx = const_cast<DragonContext *>(ctx);
    if (result) *result = b;
    if (device_ptr) *device_ptr = host;
    return nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceContext_createBuffer_owning(
    const DragonBuffer **result, const DragonContext *ctx, void *device_ptr,
    size_t len, size_t elem_size, bool owning) {
    auto *b = new DragonBuffer();
    b->mem = (cl_mem)device_ptr;
    b->bytes = len * elem_size;
    b->ctx = const_cast<DragonContext *>(ctx);
    b->owning = owning;
    if (result) *result = b;
}

__declspec(dllexport) int64_t AsyncRT_DeviceBuffer_bytesize(const DragonBuffer *b) {
    return b ? (int64_t)b->bytes : 0;
}

__declspec(dllexport) void AsyncRT_DeviceBuffer_retain(const DragonBuffer *b) {
    if (b) const_cast<DragonBuffer *>(b)->rc.fetch_add(1);
}

/* The stdlib grew this accessor after the ABI spec was generated: copies
 * route through the buffer's owning context. A borrow, not a retain. */
__declspec(dllexport) DragonContext *AsyncRT_DeviceBuffer_context(const DragonBuffer *b) {
    return b ? b->ctx : nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceBuffer_release(const DragonBuffer *b) {
    if (!b) return;
    auto *x = const_cast<DragonBuffer *>(b);
    if (x->rc.fetch_sub(1) != 1) return;
    if (x->hostPtr) free(x->hostPtr);
    else if (x->mem && x->owning) clReleaseMemObject(x->mem);
    delete x;
}

/* ---- transfers ---------------------------------------------------------- */

__declspec(dllexport) const char *AsyncRT_DeviceContext_HtoD_async(
    const DragonContext *ctx, const DragonBuffer *dst, const void *src) {
    if (!ctx || !dst) return errf("HtoD_async: null argument");
    if (getenv("DRAGONRT_TRACE_COPY"))
        fprintf(stderr, "[dragonrt] HtoD_async\n");
    /* CL_TRUE: see the transfer-coherency note above DtoD_async. */
    cl_int e = clEnqueueWriteBuffer(ctx->defaultStream->q, dst->mem, CL_TRUE, 0,
                                    dst->bytes, src, 0, nullptr, nullptr);
    return e == CL_SUCCESS ? nullptr : errf("clEnqueueWriteBuffer failed: %d", e);
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_DtoH_async(
    const DragonContext *ctx, void *dst, const DragonBuffer *src) {
    if (!ctx || !src) return errf("DtoH_async: null argument");
    if (getenv("DRAGONRT_TRACE_COPY"))
        fprintf(stderr, "[dragonrt] DtoH_async\n");
    /* CL_TRUE: see the transfer-coherency note above DtoD_async. */
    cl_int e = clEnqueueReadBuffer(ctx->defaultStream->q, src->mem, CL_TRUE, 0,
                                   src->bytes, dst, 0, nullptr, nullptr);
    return e == CL_SUCCESS ? nullptr : errf("clEnqueueReadBuffer failed: %d", e);
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_DtoD_async(
    const DragonContext *ctx, const DragonBuffer *dst, const DragonBuffer *src) {
    if (!ctx || !dst || !src) return errf("DtoD_async: null argument");
    size_t n = dst->bytes < src->bytes ? dst->bytes : src->bytes;
    if (getenv("DRAGONRT_TRACE_COPY"))
        fprintf(stderr,
                "[dragonrt] DtoD dst{mem=%p host=%p %zub} src{mem=%p host=%p "
                "%zub} n=%zu\n",
                (void *)dst->mem, dst->hostPtr, dst->bytes, (void *)src->mem,
                src->hostPtr, src->bytes, n);

    /* Transfer coherency on OpenCLOn12, measured 2026-08-20: with CL_FALSE,
     * a WriteBuffer followed by an NDRange on the same in-order queue hands
     * the kernel stale data (most of the buffer), and even with clFinish
     * between them the first 16 bytes arrive corrupted. Every host-touching
     * transfer is therefore blocking (CL_TRUE). The ABI's _async contract is
     * still honoured -- the caller synchronizes before reading results -- so
     * this trades copy/compute overlap we were not using for correctness.
     */
    /* The stdlib evolved past the ABI spec here: every buffer-to-buffer copy
     * -- including host<->device -- now arrives through this one entry point,
     * and a host buffer carries hostPtr with mem null. Dispatch on shape
     * rather than assuming two cl_mems, or the copy dies with
     * CL_INVALID_MEM_OBJECT (-38). */
    if (src->hostPtr && dst->hostPtr) {
        memcpy(dst->hostPtr, src->hostPtr, n);
        return nullptr;
    }
    if (src->hostPtr) {
        cl_int e = clEnqueueWriteBuffer(ctx->defaultStream->q, dst->mem,
                                        CL_TRUE, 0, n, src->hostPtr, 0,
                                        nullptr, nullptr);
        return e == CL_SUCCESS ? nullptr
                               : errf("clEnqueueWriteBuffer failed: %d", e);
    }
    if (dst->hostPtr) {
        cl_int e = clEnqueueReadBuffer(ctx->defaultStream->q, src->mem,
                                       CL_TRUE, 0, n, dst->hostPtr, 0,
                                       nullptr, nullptr);
        return e == CL_SUCCESS ? nullptr
                               : errf("clEnqueueReadBuffer failed: %d", e);
    }
    cl_int e = clEnqueueCopyBuffer(ctx->defaultStream->q, src->mem, dst->mem, 0, 0, n,
                                   0, nullptr, nullptr);
    return e == CL_SUCCESS ? nullptr : errf("clEnqueueCopyBuffer failed: %d", e);
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_setMemory_async(
    const DragonContext *ctx, const DragonBuffer *dst, uint64_t val,
    size_t val_size) {
    if (!ctx || !dst) return errf("setMemory_async: null argument");
    cl_int e = clEnqueueFillBuffer(ctx->defaultStream->q, dst->mem, &val, val_size, 0,
                                   dst->bytes, 0, nullptr, nullptr);
    return e == CL_SUCCESS ? nullptr : errf("clEnqueueFillBuffer failed: %d", e);
}

/* ---- streams ------------------------------------------------------------ */

__declspec(dllexport) const char *AsyncRT_DeviceContext_createStream(
    const DragonStream **result, int priority, const DragonContext *ctx) {
    if (!ctx) return errf("createStream: null context");
    cl_int err = CL_SUCCESS;
    auto *c = const_cast<DragonContext *>(ctx);
    cl_command_queue q = clCreateCommandQueue(c->cl, c->dev, 0, &err);
    if (err != CL_SUCCESS) return errf("clCreateCommandQueue failed: %d", err);
    auto *s = new DragonStream();
    s->q = q;
    s->ctx = c;
    {
        std::lock_guard<std::mutex> g(c->lock);
        c->streams.push_back(s);
    }
    if (result) *result = s;
    return nullptr;
}

__declspec(dllexport) const char *AsyncRT_DeviceContext_stream(
    const DragonStream **result, const DragonContext *ctx) {
    if (!ctx) return errf("stream: null context");
    if (result) *result = ctx->defaultStream;
    return nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceStream_retain(const DragonStream *s) {
    if (s) const_cast<DragonStream *>(s)->rc.fetch_add(1);
}

__declspec(dllexport) void AsyncRT_DeviceStream_release(const DragonStream *s) {
    /* Streams are owned by their context and freed with it. */
    if (s) const_cast<DragonStream *>(s)->rc.fetch_sub(1);
}

__declspec(dllexport) const char *AsyncRT_DeviceStream_synchronize(
    const DragonStream *s) {
    if (!s) return errf("stream synchronize: null stream");
    cl_int e = clFinish(s->q);
    return e == CL_SUCCESS ? nullptr : errf("clFinish failed: %d", e);
}

/* ---- kernels ------------------------------------------------------------
 * `data` is the compiled module blob. Two forms are accepted:
 *   - SPIR-V, detected by its magic number 0x07230203, loaded via
 *     clCreateProgramWithIL. This is the form Mojo will emit once KGEN grows a
 *     SPIR-V path (W3).
 *   - OpenCL C source, so the runtime can be exercised with hand-written
 *     kernels today, before that codegen exists.
 */

static const uint32_t kSpirvMagic = 0x07230203u;

__declspec(dllexport) const char *AsyncRT_DeviceContext_loadFunction(
    const DragonFunction **result, const DragonContext *ctx, const char *moduleName,
    const char *functionName, const char *data, size_t dataLen,
    int32_t maxDynamicSharedBytes, const char *debugLevel, int32_t optimizationLevel) {
    if (!ctx || !data || !functionName) return errf("loadFunction: null argument");
    auto *c = const_cast<DragonContext *>(ctx);
    cl_int err = CL_SUCCESS;
    cl_program prog = nullptr;

    bool isSpirv = dataLen >= 4 && memcmp(data, &kSpirvMagic, 4) == 0;

    /* DRAGONRT_DUMP_SPV=<dir>: write every SPIR-V module byte-exactly as the
     * driver will see it, BEFORE ingestion. This exists because bisecting a
     * kernel-creation failure needs the real emitted module, not a
     * reconstruction - and this hook captures it with no compiler round-trip.
     * Filenames are the kernel name truncated to a sane length; mangled Mojo
     * names run to hundreds of characters. */
    if (isSpirv) {
        if (const char *dumpDir = getenv("DRAGONRT_DUMP_SPV")) {
            char fname[512];
            char safe[101] = {0};
            size_t j = 0;
            for (size_t i = 0; functionName[i] && j < 100; ++i) {
                char ch = functionName[i];
                safe[j++] = (isalnum((unsigned char)ch) || ch == '_') ? ch : '_';
            }
            static std::atomic<int> dumpCounter{0};
            snprintf(fname, sizeof(fname), "%s/%03d_%s.spv", dumpDir,
                     dumpCounter.fetch_add(1), safe);
            if (FILE *f = fopen(fname, "wb")) {
                fwrite(data, 1, dataLen, f);
                fclose(f);
            }
        }
    }

    if (isSpirv) {
        if (!c->ilCreate)
            return errf(
                "SPIR-V module supplied but the selected OpenCL platform "
                "('%s') cannot ingest IL. On this machine the native QUALCOMM "
                "driver has no SPIR-V path; the OpenCLOn12 platform does "
                "(unset DRAGONRT_PREFER=native to allow it).",
                c->platName.c_str());
        prog = c->ilCreate(c->cl, data, dataLen, &err);
        if (err != CL_SUCCESS)
            return errf("clCreateProgramWithILKHR failed: %d", err);
    } else {
        const char *src = data;
        size_t len = dataLen;
        prog = clCreateProgramWithSource(c->cl, 1, &src, &len, &err);
        if (err != CL_SUCCESS) return errf("clCreateProgramWithSource failed: %d", err);
    }

    if (clBuildProgram(prog, 1, &c->dev, nullptr, nullptr, nullptr) != CL_SUCCESS) {
        size_t n = 0;
        clGetProgramBuildInfo(prog, c->dev, CL_PROGRAM_BUILD_LOG, 0, nullptr, &n);
        std::string log(n ? n : 1, '\0');
        if (n) clGetProgramBuildInfo(prog, c->dev, CL_PROGRAM_BUILD_LOG, n, &log[0],
                                     nullptr);
        clReleaseProgram(prog);
        return errf("build of module '%s' failed:\n%s",
                    moduleName ? moduleName : "?", log.c_str());
    }

    cl_kernel k = clCreateKernel(prog, functionName, &err);
    if (err != CL_SUCCESS) {
        /* The requested name is several hundred characters of Mojo mangling,
         * so "not found" and "found but rejected" look identical from the
         * error code alone. Report what the built program actually contains:
         * an empty list means the translation dropped the entry point, a
         * populated one means the names disagree. */
        std::string names;
        size_t n = 0;
        if (clGetProgramInfo(prog, 0x1166 /* CL_PROGRAM_KERNEL_NAMES */, 0,
                             nullptr, &n) == CL_SUCCESS && n) {
            names.assign(n, ' ');
            clGetProgramInfo(prog, 0x1166, n, &names[0], nullptr);
        }
        cl_uint count = 0;
        clGetProgramInfo(prog, 0x1167 /* CL_PROGRAM_NUM_KERNELS */,
                         sizeof(count), &count, nullptr);
        clReleaseProgram(prog);
        return errf("clCreateKernel failed: %d\n"
                    "  wanted (%zu chars): %s\n"
                    "  program has %u kernel(s): %s",
                    err, strlen(functionName), functionName, count,
                    names.empty() ? "(none)" : names.c_str());
    }

    auto *f = new DragonFunction();
    f->prog = prog;
    f->kern = k;
    f->ctx = c;
    if (result) *result = f;
    return nullptr;
}

__declspec(dllexport) void AsyncRT_DeviceFunction_retain(const DragonFunction *f) {
    if (f) const_cast<DragonFunction *>(f)->rc.fetch_add(1);
}

__declspec(dllexport) void AsyncRT_DeviceFunction_release(const DragonFunction *f) {
    if (!f) return;
    auto *x = const_cast<DragonFunction *>(f);
    if (x->rc.fetch_sub(1) != 1) return;
    if (x->kern) clReleaseKernel(x->kern);
    if (x->prog) clReleaseProgram(x->prog);
    delete x;
}

/* Launch. Dimensions are uint32_t deliberately - see the file header.
 *
 * `args` is an array of pointers to argument values, CUDA-style. `argSizes`
 * gives each argument's size and may be null, in which case pointer-sized is
 * assumed (which is right for buffer arguments and wrong for scalars, so Mojo
 * supplies it whenever scalars are involved).
 */
__declspec(dllexport) const char *AsyncRT_DeviceContext_enqueueFunctionDirect(
    const DragonContext *ctx, const DragonFunction *func, uint32_t gridX,
    uint32_t gridY, uint32_t gridZ, uint32_t blockX, uint32_t blockY, uint32_t blockZ,
    uint32_t sharedMemBytes, void *attributes, uint32_t numAttributes, void **args,
    uint32_t argCount, uint64_t *argSizes) {
    if (!ctx || !func) return errf("enqueueFunctionDirect: null argument");

    /* DRAGONRT_TRACE_ARGS: what the host actually handed us, per argument.
     * The sizes are the half that is easy to get wrong and impossible to see:
     * a null argSizes silently makes every argument pointer-sized, which is
     * right for buffers and wrong for scalars, and shows up only as
     * CL_INVALID_ARG_SIZE on whichever argument happens to be a scalar. */
    if (getenv("DRAGONRT_TRACE_ARGS"))
        fprintf(stderr, "[dragonrt] argCount=%u argSizes=%p\n", argCount,
                (void *)argSizes);
    for (uint32_t i = 0; i < argCount; ++i) {
        size_t sz = argSizes ? (size_t)argSizes[i] : sizeof(void *);
        if (getenv("DRAGONRT_TRACE_ARGS"))
            fprintf(stderr, "[dragonrt]   arg %u size %zu\n", i, sz);
        cl_int e = clSetKernelArg(func->kern, i, sz, args[i]);
        if (e != CL_SUCCESS)
            return errf("clSetKernelArg(%u, size=%zu) failed: %d", i, sz, e);
    }

    /* Mojo speaks CUDA-style grid-of-blocks; OpenCL wants a global size in
     * work-items. Multiply through. */
    size_t gws[3] = {(size_t)gridX * blockX, (size_t)gridY * blockY,
                     (size_t)gridZ * blockZ};
    size_t lws[3] = {blockX, blockY, blockZ};

    cl_int e = clEnqueueNDRangeKernel(ctx->defaultStream->q, func->kern, 3, nullptr,
                                      gws, lws, 0, nullptr, nullptr);
    return e == CL_SUCCESS ? nullptr : errf("clEnqueueNDRangeKernel failed: %d", e);
}

} /* extern "C" */
